{
 "title": "Mini Order API",
 "tags": [
  "fastapi",
  "prometheus",
  "orders"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Taxa de erro",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_http_requests_total{status_code=~\"5..|4..\"}[1m])) / sum(rate(ecommerce_http_requests_total[1m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecommerce_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Pedidos ativos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_orders", "legendFormat": "ativos" }
   ]
  },
  {
   "title": "Trafego por rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_http_requests_total[1m])) by (route, status_code)",
     "legendFormat": "{{route}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Pedidos por status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "orders_by_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Latencia do pagamento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "pagamento p95"
    }
   ]
  },
  {
   "title": "Pagamentos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(ecommerce_payments_total{status=\"failed\"}[1m]))",
     "legendFormat": "falhas/s"
    },
    {
     "expr": "sum(rate(ecommerce_payments_total{status=\"succeeded\"}[1m]))",
     "legendFormat": "pagos/s"
    }
   ]
  }
 ]
}